### ISSUE TITLE
Background Player Issue: I have killed sample SDK app still player notification is appearing in notification bar.

### ISSUE THREAD

**Issue by YudizAndroidYagnik** [THEOplayer/samples-android-sdk#26]
Issue is faced when I am checking the player sdk sample app for Background Player. I have killed the app but the application controllers is stilled aspiring in notification panel. Even I am swipe to right side still it is not disappearing.

> Device info:
- Device: Poco X3 pro
- Android Version: 12

Here I am screenshot of the issue.
https://drive.google.com/drive/folders/104zxZM-emd0q48da9ZW9gpUTQpcBK1W8?usp=sharing

**Comment by ceyhun-o** [comment]
Hi @YudizAndroidYagnik,

Please reach out to us from our [Service Desk](https://opentelly.atlassian.net/servicedesk/customer/portal/1) if you are still having this issue so can take a look at it.

Kind regards,
Ceyhun
