### ISSUE TITLE
Cast sender Android issue

### ISSUE THREAD

**Issue by 1nikolas** [THEOplayer/samples-android-sdk#27]
Hello. I'm trying to implement an android cast sender by following your guide. In your guide you say:

> The cast button is visible when a receiver that supports the app is discovered. 

But the cast button is always visible for me for some reason and I can't find a way to automatically hide it. 

After a bit of debugging I found out that the device scan is only initiated after I click the Cast button which is not the functionality i would expect. 

Any help is appreciated.
Thanks

**Comment by 1nikolas** [comment]
As a side note, the Google Photos app works exactly the same now. It seems like they made this change in a library update. Buy why?

**Comment by 1nikolas** [comment]
I think this is it?

https://developers.google.com/cast/docs/release-notes#december-4,-2023

> Updated to depend on androidx.mediarouter:mediarouter:1.6.0-beta01. This makes MediaRouteButtons always visible by default. This allowed for decreasing the scenarios where Cast device discovery is started automatically without user action.

**Comment by ceyhun-o** [comment]
Hi @1nikolas,

Please reach out to us from our [Service Desk](https://opentelly.atlassian.net/servicedesk/customer/portal/1) and share all the details such as reproduction steps, player version and a minimal sample app if you are having an issue with the player SDK.

Kind regards,
Ceyhun
